# Name
# Trigger / Event
# Jobs
  # Steps

name: React CI

on: push

jobs: 
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/ checkout@v4

      - name: Install Dependencies
        run: npm Install

      - name: Use Node.js
        uses: actions/setup-node@4
        with:
          node-version: 18

      - name: Run test
        run: npm run test
